mis:
  build: "https://github.com/trflagg/MakeItSo.git#develop"
  ports:
    - "3000:3000"
  volumes:
    - '.:/usr/src/app'
  links:
    - mongo:mongo
  environment:
    NODE_ENV: development
    DB_ENV: compose
mongo:
  image: "mongo:3.2"
sass:
  build: "https://github.com/trflagg/sass-docker.git"
  volumes:
    - '.:/src'
  command:  --watch /src/client/sass:/src/client/build/css
browserify:
  build: "https://github.com/trflagg/browserify-docker.git"
  volumes:
    - '.:/src'
  environment:
    NODE_PATH: '/src/node_modules/'
  command: --list /src/client/js/main.js -o /src/client/build/js/main.js